##############################
# Custom Gitleaks Ruleset
##############################

[allowlist]
# ignore files or paths here (optional)
# paths = ["README.md"]

##############################
# Rules
##############################

[[rules]]
id = "aws-access-key"
description = "AWS Access Key ID"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws", "key", "cloud"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws(.{0,20})?(secret)?(.{0,20})?['\"=:\s]{1,6}[0-9a-zA-Z\/+]{40}'''
tags = ["aws", "key", "cloud"]

[[rules]]
id = "github-token"
description = "GitHub Personal Access Token"
regex = '''ghp_[0-9a-zA-Z]{36,255}'''
tags = ["github", "token", "api"]

[[rules]]
id = "generic-secret"
description = "Generic secret key or token"
regex = '''(?i)(apikey|token|secret|key)[\s:=]+['"]?[a-z0-9_\-]{8,45}['"]?'''
tags = ["generic", "custom", "secret"]


